library(plyr)
library(tidyverse)
library(magrittr)
library(stringr)
library(readxl)
library(xml2)
# library(data.tree)
library(forcats)

source('src/clean/simple.R')
source('src/transform/count_geo.R')
source('src/map/index.R')
