---
title: "R Notebook"
output: html_notebook
---

```{r}
```


```{r}
    # replace NA with empty string so `str_c` can work
    # mutate_at(vars(contains('coverage')),
    #           function(x) replace(x, is.na(x), '')) %>%
    # mutate(
      # coverage = str_c(coverage1, coverage2, coverage3, sep = '; ') %>%
      #   str_to_title() %>%
      #   str_replace_all('\\.+', ' ') %>%
      #   str_trim() %>%
      #   str_replace_all('(?i)\\band ', '') %>%
      #   # when coverage is `MA`, it is often extraneous and inaccurate
      #   # Check: View(sites %>% filter(str_detect(coverage, '\\bMa\\b')))
      #   str_replace_all('[,;] Ma[; ]*$', '') %>%
      #   str_replace('\\bMa\\b', 'MA') %>%
      #   str_split(' *[,;] *') %>%
      #   map_chr(function(x) {
      #     x %<>% unique() %>%
      #       # remove empty string so to clean the end output
      #       .[. != '']
      #     if (length(x) == 0) {
      #       x <- NA
      #     } else {
      #       x <- str_c(x, collapse='; ')
      #     }
      #     x
      #   }),
    # ) %>%
```

